name: Python Type Checking

on: [push, pull_request]

jobs:
  ruff:
    name: Run mypy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install typing depenencies
      run: pip install mypy pydantic
    - name: Run mypy
      run: mypy .
